apiVersion: v1

kind: Pod

metadata:
  namespace: django-app
  name: todo-pod

spec:

  containers:

  - name: todo-app

    image: trainwithshubham/django-todo:latest

    ports:

    - containerPort: 8000

